log_level: INFO
input:
  address:
    host: localhost
    port: 1234
  video:
    enable: true
    uri: file:///home/example/path/pipeless/examples/cats/cats.mp4
output:
  address:
    host: localhost
    port: 1237
  video:
    enable: true
    uri: file:///home/example/path/pipeless/examples/cats/cats-output.mp4
worker:
  n_workers: 1
