log_level: INFO
input:
  address:
    host: localhost
    port: 1234
  video:
    enable: true
    uri: 'file:///home/miguelaeh/projects/pipeless/examples/cats/cats.mp4'
      # uri: 'rtmp://localhost:1935/twich/input'
output:
  address:
    host: localhost
    port: 1237
  video:
    enable: true
    uri: file:///home/miguelaeh/projects/pipeless/examples/cats/cats-output.mp4
      #uri: rtmp://localhost:1935/twich/output
worker:
  n_workers: 1
