input:
  address:
    host: localhost
    port: 1234
  video:
    enable: true
    uri: 'file:///home/path/pipeless/examples/onnx-yolo/input.mp4'
log_level: INFO
output:
  address:
    host: localhost
    port: 1237
  video:
    enable: true
    uri: 'file:///home/path/pipeless/examples/onnx-yolo/output.mp4'
plugins:
  order: 'draw'
worker:
  n_workers: 1
  inference:
    model_uri: 'file:///home/path/pipeless/examples/onnx-yolo/yolov8n.onnx'
    image_shape_format: 'channels, height, width'
    
