input:
  address:
    host: localhost
    port: 1234
  video:
    enable: true
    uri: file:///home/miguelaeh/projects/pipeless-2/examples/text-overlay/book-video.mp4
log_level: INFO
output:
  address:
    host: localhost
    port: 1237
  video:
    enable: true
    uri: rtmp://localhost:1935/twich/test
worker:
  n_workers: 1
