[tool.poetry]
name = "pupila-cli"
version = "0.1.0"
description = "CLI component of the pupila computer vision framework"
authors = ["Miguel Angel Cabrera Minagorri <devgorri@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "cli"}]

[tool.poetry.dependencies]
python = "^3.10"
typer = {version = "^0.9.0", extras = ["all"]}
pyyaml = "^6.0.1"
pupila = "^0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pupila-cli = "cli.main:app"
