[tool.poetry]
name = "pipeless"
version = "0.1.0"
description = "A framework to build and deploy multimodal perception apps in minutes without worrying about multimedia pipelines"
authors = ["Miguel Angel Cabrera Minagorri <devgorri@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
rich = "^13.4.2"
pynng = "^0.7.2"
numpy = "^1.25.2"
pygobject = "^3.44.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
