input:
  address:
    host: localhost
    port: 1234
  video:
    enable: true
    uri: file:///home/miguelaeh/projects/pipeless-2/examples/pose/woman-walking.mp4
log_level: INFO
output:
  address:
    host: localhost
    port: 1237
  video:
    enable: true
    uri: file:///home/miguelaeh/projects/pipeless-2/examples/pose/output.mp4
worker:
  n_workers: 1
