apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-scripts-configmap
data:
  download-application.sh: |
    #!/bin/bash
    if [[ -z "{{ .Values.worker.application.git_repo }}" ]]; then
      echo "Missing worker.application.git_repo URL"
      exit 1
    fi
    git clone {{ .Values.worker.application.git_repo }} /tmp/app
    if [[ -n "{{ .Values.worker.application.subPath }}" ]]; then
      cp -R /tmp/app/{{ .Values.worker.application.subPath }}/* /app
    else
      cp -R /tmp/app/* /app
    fi