input:
  address:
    host: localhost
    port: 1234
  video:
    enable: true
    uri: v4l2
log_level: INFO
output:
  address:
    host: localhost
    port: 1237
  video:
    enable: true
    uri: screen
plugins:
  order: 'yolov8,draw'
worker:
  n_workers: 1
